version: '3'
services: 
  db:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    container_name: postgres-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  nestjs:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: acclaimedhw/nest-and-postgres-api:latest
    environment: 
      - DB_TYPE=${DB_TYPE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASS=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - POSTGRES_SYNC=false
      - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_PORT=${TYPEORM_PORT}
      - APP_EXPIRES=${APP_EXPIRES}
      - APP_PORT=${APP_PORT}
    ports: 
      - "3000:3000" # expose-to-the-world : only-in-the-docker
    container_name: acclaimedhwapi-nest-app
    depends_on: 
      - db
    volumes: 
      - .:/app
      - /app/node_modules
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports: 
      - "8080:80"
    volumes: 
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on: 
      - db
volumes:
  pgdata:
  pgadmin-data:
